### ISSUE TITLE
useScreenClass doesn't return values from current context

### ISSUE THREAD

**Issue by timothyarmes** [sealninja/react-grid-system#119]
I've been trying to use useScreenClass in combination with , for example, `<Col xs={12} lg={6}>`.

Unfortunately this doesn't work since `Col` is correctly getting the current screen class from the provider, where as `useScreenClass` uses the window. As a result, the screen classes returned in each case aren't in sync.

**Comment by oziks** [comment]
@timothyarmes It is possible to pass a `source` argument to the `useScreenClass` hook. The source must be a reference to an element.

Example of use here.

```js
const App = () => {
  const elementRef = useRef(null);
  const screenClass = useScreenClass(elementRef);

  console.log({ screenClass });

  return <div ref={elementRef} />;
};
```
In the hope that it will help you.

**Comment by gerbenmeyer** [comment]
Maybe this is something I should add to the documentation :smile:
