### ISSUE TITLE
setConfiguration not working with functional components?

### ISSUE THREAD

**Issue by heaversm** [sealninja/react-grid-system#127]
Hi - I think I'm implementing this wrong - but I cannot seem to configure my app for anything but 12 column grid. In `App.js` I have:

```
function App() {
  useEffect(() => {
    setConfiguration({ defaultScreenClass: 'sm', gridColumns: 20 });
  });
  
  return (
    <div className="App">
      <ScreenClassProvider>
        <SiteHeader/>
      </ScreenClassProvider>
    </div>
  );
}
```

and in `<SiteHeader/>` I have simply:

```
import './SiteHeader.scss';
import React from 'react';
import { Container, Row, Col } from 'react-grid-system';

const SiteHeader = (props) => {
  return (
    <Container className="SiteHeader">
      <Row className="site_header__container">
      <Col sm={4} className="site_header__title_container">
          ...
        </Col>
        <Col sm={16} className="site_header__search_container">
          ...
        </Col>
      </Row>
    </Container>
  );
};
export default SiteHeader;
```

If I make it `sm={8}` for the search container it will stay in the same row, but if I make it larger (essentially total cols > the default 12), then it wraps to the next line. How to fix this?

**Comment by gerbenmeyer** [comment]
`setConfiguration` is designed for setting a global configuration before rendering anything. Calling it won't trigger a rerender. Hence, better call it before the initial render.
