### ISSUE TITLE
Reverse responsive column position?

### ISSUE THREAD

**Issue by anoraxdev** [sealninja/react-grid-system#138]
Is there a property that I can change in order to make the left column move down instead of the right? Especially for responsive design.

**Comment by gerbenmeyer** [comment]
Yes, you can just use push and pull of Col.

Op vr 10 apr. 2020 19:47 schreef Andreas J. Ellerbrock <
notifications@github.com>:

**Comment by anoraxdev** [comment]
So I have columns 
[1][2]
and when the screen shrinks I want them to be 
[2][1]

This is what I added but doesn't change. 
`
<Container>
     <Row>
          <Col md={6} class="col-sm-push-6 col-xs-push-6"></Col>
          <Col md={6} class="col-sm-pull-6 col-xs-pull-6"> 2</Col>
     </Row>
</Container>
`
Sorry for the trouble, I'm new to this. What am I doing wrong?

**Comment by anoraxdev** [comment]
Solved it, set the row's style property to 
{{ flexWrap: 'wrap-reverse' }}
