### ISSUE TITLE
Grid renders differently in production vs development (Gatsby)

### ISSUE THREAD

**Issue by jaydenkieran** [sealninja/react-grid-system#140]
Hi, I'm using Gatsby and react-grid-system to build a basic static site for a client (apologies, I'm not able to show the site here). It should be responsive, and Rows/Cols should render vertically on mobile (as opposed to side-by-side on desktop). It uses two rows - one row with one col, and the other row with two cols (these two are configured with `xs={12} md={6}`).

Expected behaviour on desktop:

[Col]
[Col] [Col]

Expected behaviour on mobile:

[Col]
[Col]
[Col]

When using `gatsby develop`, this behaviour occurs as expected. After building the project with `gatsby build` and viewing the built index.html (locally or on a deployed server), the grid does not "collapse" as expected when resizing down to `sm` breakpoints.

I'm not sure if this is related to #126, it seems that it could be at first glance. Sorry if this isn't the best explanation!

(A temporary fix for this is to deploy two versions of the site, using `<ScreenClassProvider fallbackScreenClass={'xs'}>` to force the mobile view, but this is not good - we need one static site working for both desktop and mobile)

**Comment by ivanralevic** [comment]
Having same issue

**Comment by gerbenmeyer** [comment]
This is resolved in version 6.4.0, by means of two-pass-rendering. Please let me know if you are still having issues!
