### ISSUE TITLE
equal height columns

### ISSUE THREAD

**Issue by birthdaycorp** [sealninja/react-grid-system#151]
Is it possible to have equal height Cols in a Row? Setting the style prop to `height: 100%` has no impact.

**Comment by gerbenmeyer** [comment]
`<Row align="stretch">` is basically for that.

**Comment by birthdaycorp** [comment]
So technically this should make the columns in aRow equal height to the largest?
```
<Container fluid>
 <Row align="stretch" justify="center">
  <Col sm={12} md={12} lg={6} xl={4}>
   <div>test</div>
  </Col>
  <Col sm={12} md={12} lg={6} xl={4}>
   <ul>
    <li>test</li>
    <li>test</li>
    <li>test</li>
    <li>test</li>
   </ul>
  </Col>
 </Row>
</Container>
```

**Comment by EngineNeo** [comment]
This did not work for me, were you able to get this to work?
