### ISSUE TITLE
Bug: extraneous 15px whitespace at both ends of a container

### ISSUE THREAD

**Issue by ArthurClemens** [sealninja/react-grid-system#175]
In order to place a grid inside a content container, the left and right sides of the container should be aligned with the parent container, and not have any paddings itself.

Currently the container adds extra paddings of 15px.

Take for example the [documentation of grid gutters](https://developer.mozilla.org/en-US/docs/Glossary/Gutters) that shows whitespace (gutters) between columns, but not outside of it.

[CodeSandbox example how the grid should behave](https://codesandbox.io/s/react-grid-system-test-b1qvm)

**Comment by veloware** [comment]
I ran into the same problem, and to expand further on your codesandbox, once you remove the padding at the container, you now have horizontal scroll when at the smaller breakpoint :(

**Comment by stefanzmf** [comment]
whdym? boostrap (v.5.1.3) works exactly the same https://codesandbox.io/s/bootstrap-grid-sandbox-forked-n7kpx?file=/index.html:888-892

**Comment by ArthurClemens** [comment]
Hmm, on second look my example doesn't look right either. Will close this.
