### ISSUE TITLE
How to add additional breakpoints?

### ISSUE THREAD

**Issue by giovannipds** [sealninja/react-grid-system#88]
I know we are using Bootstrap 4 breakpoints but how could we set more breakpoints? Example, an extra breakpoint like `xxl`, which responds to `1600px` above.

Taking a quick look at the library, every code relies on strings / types for the screen size names, I really think we should use that dynamically somehow, if this isn't possible yet.
```javascript
import { setConfiguration } from 'react-grid-system';

// probably won't work as expected
setConfiguration({
    breakpoints: [576, 768, 992, 1200, 1600],
    containerWidths: [540, 750, 960, 1140, 1540],
});
```

Looking at `utils.js`, that's a `const`:
```javascript
export const screenClasses = ['xs', 'sm', 'md', 'lg', 'xl'];
// we should be able to set this anyhow
```

**Comment by gerbenmeyer** [comment]
This is currently not supported, maybe some time in the future though :smile:

**Comment by tonix-tuft** [comment]
I think this would be a great idea, at least having the possibility to use an `xxl` breakpoint on the `Col` component, e.g.:

```
                        <Container fluid>
                            <Row>
                                <Col xxl={8} // <--- This width shows up at e.g. 1600px width.
                                         xl={6}
                                         ...and so on...
                                >...</Col>
                                ...
                           </Row>
```

On very large screens, it would be great to have the possibility to change the layout when a threshold of e.g. 1600px is reached.

What do you think?

**Comment by giovannipds** [comment]
@tonix-tuft this issue's the reason that I didn't use this package at first look. =S

**Comment by tonix-tuft** [comment]
@giovannipds What did you end up using?

**Comment by gerbenmeyer** [comment]
The main issue is that currently, the 5 screen classes are hard-coded. So is only adding `xxl` sufficient for now? That should be rather straightforward, but allowing a custom amount of classes would require a huge refactor.

**Comment by tonix-tuft** [comment]
Thank you for your reply @gerbenmeyer! Yes, for me (and I guess for others too), it would be more than enough to have at least an additional `xxl` option for now, let's say at `1600px`.
This would be very useful when dealing with very large screens as it will allow to create a custom layout for them when the width is `>= 1600px`.

This way, we will have, e.g.:

 * xs - [0, 575]
 * sm - [576, 767]
 * md - [768, 991]
 * lg - [992, 1199]
 * xl - [1200, 1599] &nbsp;&nbsp;&nbsp;<--- **Now with an upper threshold of 1599**
 * __xxl - [1600, +inf)__ &nbsp;&nbsp;&nbsp;<--- **NEW**

Would love to have this option and to hear what others think! Of course, `1600px` is just my suggestion, but I think it is a reasonable value to differentiate between extra large and very extra large screens.

Thank you!

**Comment by gerbenmeyer** [comment]
So `xxl` is there in v7. Enjoy :smile:
