### ISSUE TITLE
Add `useScreenClass` hook as alternate option to `ScreenClassRender`

### ISSUE THREAD

**Issue by CarlosGines** [sealninja/react-grid-system#99]
Hooks are an alternate option to render props in most cases. They reduce nesting in code and provide a simpler syntax.

We could make use of them to provide an alternate option to `ScreenClassRender`:
```
const screenClass = useScreenClass();
```

**Comment by gerbenmeyer** [comment]
Not using hooks myself just yet, but sounds like a good idea, so feel free to make a PR for this!

**Comment by CarlosGines** [comment]
I thought of it, what I’m not sure yet is a good way to keep the peer dependency on react ^16.0.0 and not bumping it to ^16.8.0, where hooks are available.

**Comment by gerbenmeyer** [comment]
Agreed, so I'll close this for now :smiley:

**Comment by MichalSzorad** [comment]
Alternatively, you can use `const screenClass = useContext(ScreenClassContext)`; You can try it on [this codesandbox demo](https://codesandbox.io/embed/beautiful-banzai-yzr69), unfortunatelly, there are no typings for exportet member `ScreenClassContext`.

However, the `useScreenClass` hook would be great.

**Comment by gerbenmeyer** [comment]
Just released v6, which hase the `useScreenClass` hook!
